version: '3'
services:
  app:
    build: .
    volumes:
     - .:/code
    depends_on:
      - mariadb
  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
    volumes:
      - ./conf:/etc/mysql/conf.d
    ports: 
      - "3306:3306"