CREATE TABLE dry_season_act (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  district_30 VARCHAR(255),
  ward_30 VARCHAR(255),
  village_30 VARCHAR(255),
  hhid_30 VARCHAR(255),
  dry_rain_act_pos VARCHAR(255),
  dry_rain_activity_type VARCHAR(255),
  dry_rain_activities_other VARCHAR(255),
  dry_rain_activity_Activity_date VARCHAR(255),
  dry_rain_activity_Hh_male_no VARCHAR(255),
  dry_rain_activity_Hh_male_days VARCHAR(255),
  dry_rain_activity_Hh_male_hrs_days VARCHAR(255),
  dry_rain_activity_Hh_female_no VARCHAR(255),
  dry_rain_activity_Hh_female_days VARCHAR(255),
  dry_rain_activity_Hh_female_hrs_day VARCHAR(255),
  dry_rain_activity_Hh_child_no VARCHAR(255),
  dry_rain_activity_Hh_child_days VARCHAR(255),
  dry_rain_activity_Hh_child_hrs_day VARCHAR(255),
  dry_rain_activity_Permantly_employed_worker_no VARCHAR(255),
  dry_rain_activity_Permntly_employed_days VARCHAR(255),
  dry_rain_activity_Permntly_employed_hrs_day VARCHAR(255),
  dry_rain_activity_Unpaid_labour_no VARCHAR(255),
  dry_rain_activity_Unpaid_labour_days VARCHAR(255),
  dry_rain_activity_Unpaid_labour_hrs_day VARCHAR(255),
  dry_rain_activity_hired_no VARCHAR(255),
  dry_rain_activity_hired_hours VARCHAR(255),
  dry_rain_activity_hired_hours_day VARCHAR(255),
  dry_rain_activity_other_Total_costs VARCHAR(255)
);