CREATE TABLE forage_act (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  district_33 VARCHAR(255),
  ward_33 VARCHAR(255),
  village_33 VARCHAR(255),
  hhid_33 VARCHAR(255),
  forage_act_pos VARCHAR(255),
  forage__activity_type VARCHAR(255),
  forage__activity_other_type VARCHAR(255),
  forage__activity_date VARCHAR(255),
  forage__activity_Hh_male_no VARCHAR(255),
  forage__activity_Hh_male_days VARCHAR(255),
  forage__activity_Hh_male_hrs_days VARCHAR(255),
  forage__activity_Hh_female_no VARCHAR(255),
  forage__activity_Hh_female_days VARCHAR(255),
  forage__activity_Hh_female_hrs_day VARCHAR(255),
  forage__activity_Hh_child_no VARCHAR(255),
  forage__activity_Hh_child_days VARCHAR(255),
  forage__activity_Hh_child_hrs_day VARCHAR(255),
  forage__activity_Permantly_employed_worker_no VARCHAR(255),
  forage__activity_Permntly_employed_days VARCHAR(255),
  forage__activity_Permntly_employed_hrs_day VARCHAR(255),
  forage__activity_Unpaid_labour_no VARCHAR(255),
  forage__activity_Unpaid_labour_days VARCHAR(255),
  forage__activity_Unpaid_labour_hrs_day VARCHAR(255),
  forage__activity_hired_no VARCHAR(255),
  forage__activity_hired_hours VARCHAR(255),
  forage__activity_hired_hours_day VARCHAR(255),
  forage__activity_other_Total_costs VARCHAR(255)
);