CREATE TABLE hdds (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  district_152 VARCHAR(255),
  ward_152 VARCHAR(255),
  village_152 VARCHAR(255),
  hhid_152 VARCHAR(255),
  yesterday_celebration_feast VARCHAR(255),
  took_cereals VARCHAR(255),
  took_vitamin_rich_veges_tubers VARCHAR(255),
  took_white_tubers_roots VARCHAR(255),
  took_dark_green_leafy_veges VARCHAR(255),
  took_other_veges VARCHAR(255),
  took_vit_a_rich_fruits VARCHAR(255),
  took_other_fruits VARCHAR(255),
  took_organ_meat VARCHAR(255),
  took_flesh_meats VARCHAR(255),
  took_eggs VARCHAR(255),
  took_fish VARCHAR(255),
  took_legumes_nuts_seeds VARCHAR(255),
  took_milk_products VARCHAR(255),
  took_oils_fats VARCHAR(255),
  took_sweets VARCHAR(255),
  took_spices_condiments_beverages VARCHAR(255),
  eat_outside_home_yesterday VARCHAR(255),
  hdds_comments VARCHAR(255)
);