CREATE TABLE hh_members (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  hh_member_no INT,
  district_1 VARCHAR(255),
  ward_1 VARCHAR(255),
  village_1 VARCHAR(255),
  hhid_1 VARCHAR(255),
  hh_position VARCHAR(255),
  hhposition_name VARCHAR(255),
  hh_position_other VARCHAR(255),
  hh_age INT,
  hh_age_1 INT,
  hh_gender INT,
  Highest_completed_education VARCHAR(255),
  labour_availability VARCHAR(255),
  work_calendar VARCHAR(255),
  activmain VARCHAR(255),
  activshort VARCHAR(255),
  dry_season VARCHAR(255),
  offfarm_desc VARCHAR(255),
  offfarmwork_name VARCHAR(255),
  offfarmwork_other VARCHAR(255),
  experience VARCHAR(255),
  hh_notes VARCHAR(255)
);