CREATE TABLE livestock_act_inputs (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  district_12 VARCHAR(255),
  ward_12 VARCHAR(255),
  village_12 VARCHAR(255),
  hhid_12 VARCHAR(255),
  livestock_activity_ID VARCHAR(255),
  livestock_activity_ID_name VARCHAR(255),
  livestock_activity_breed VARCHAR(255),
  livestock_activity_breed_name VARCHAR(255),
  Livestock_activity VARCHAR(255),
  Livestock_activity_name VARCHAR(255),
  Livestock_activity_other VARCHAR(255),
  livestock_Hh_male_no VARCHAR(255),
  livestock_Hh_male_Days VARCHAR(255),
  livestock_Hh_male_hrs_day VARCHAR(255),
  livestock_Hh_female_no VARCHAR(255),
  livestock_Hh_female_Days VARCHAR(255),
  livestock_Hh_female_hours VARCHAR(255),
  livestock_Hh_child_no VARCHAR(255),
  livestock_Hh_child_Days VARCHAR(255),
  livestock_Hh_child_hours VARCHAR(255),
  livestock_Permantly_employed_worker_no VARCHAR(255),
  livestock_Permantly_Days VARCHAR(255),
  livestock_Permantly_hours VARCHAR(255),
  livestock_Unpaid_labour_no VARCHAR(255),
  livestock_Unpaid_labour_days VARCHAR(255),
  livestock_Unpaid_labour_hours VARCHAR(255),
  livestock_hired_no VARCHAR(255),
  livestock_hired_days VARCHAR(255),
  livestock_hired_hours VARCHAR(255)
);