CREATE TABLE livestock_prod_utilization (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  confirmed_livestock_no VARCHAR(255),
  district_11 VARCHAR(255),
  ward_11 VARCHAR(255),
  village_11 VARCHAR(255),
  hhid_11 VARCHAR(255),
  livestock_ID VARCHAR(255),
  livestock_prdct_codes VARCHAR(255),
  livestock_product_breed VARCHAR(255),
  livestock_product_data_period VARCHAR(255),
  production_Qty VARCHAR(255),
  production_Qty_units VARCHAR(255),
  livestock_products_Qty_sold VARCHAR(255),
  production_Qty_HH VARCHAR(255),
  production_Qty_HH_units VARCHAR(255),
  production_Qty_other VARCHAR(255),
  production_Qty_other_units VARCHAR(255),
  other_buyer VARCHAR(255),
  production_Qty_sales VARCHAR(255),
  production_Qty_sales_value VARCHAR(255),
  production_Qty_sales_gender VARCHAR(255),
  production_Qty_sales_buyer VARCHAR(255),
  production_buyer_reasons VARCHAR(255)
);