CREATE TABLE long_rains_intercrop_comp (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  long_rains_Intercrop_components VARCHAR(255),
  district_5 VARCHAR(255),
  ward_5 VARCHAR(255),
  village_5 VARCHAR(255),
  hhid_5 VARCHAR(255),
  long_rains_types_of_intercrop VARCHAR(255),
  long_rains_interCrop_products VARCHAR(255),
  long_rains_interCrop_production_Quantity VARCHAR(255),
  long_rains_interCrop_production_Quantity_units VARCHAR(255),
  long_rains_interCrop_Hhfood_consumption_Qty VARCHAR(255),
  long_rains_interCrop_Hhfood_consumption_Qty_units VARCHAR(255),
  long_rains_interCrop_Payment_in_kind_quantity VARCHAR(255),
  long_rains_interCrop_Payment_in_kind_quantity_units VARCHAR(255),
  long_rains_interCrop_other_Qty VARCHAR(255),
  long_rains_interCrop_other_Qty_units VARCHAR(255),
  long_rains_interCrop_Livestock_feeding_Qty VARCHAR(255),
  long_rains_interCrop_Livestock_feeding_Qty_units VARCHAR(255),
  long_rains_interCrop_kept_as_seed_Qty VARCHAR(255),
  long_rains_interCrop_kept_as_seed_Qty_units VARCHAR(255),
  long_rains_interCrop_sales_Qnty VARCHAR(255),
  long_rains_interCrop_Sales_quantity VARCHAR(255),
  long_rains_interCrop_Sales_units VARCHAR(255),
  long_rains_interCrop_Sales_total_value VARCHAR(255),
  long_rains_interCrop_Sales_income_control VARCHAR(255),
  long_rains_interCrop_main_buyer VARCHAR(255),
  long_rains_intercrop_products_notes VARCHAR(255),
  Long_rains_interCrop_Residue_utilisation_count VARCHAR(255)
);