CREATE TABLE manure_product_details_b (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  district_142 VARCHAR(255),
  ward_142 VARCHAR(255),
  village_142 VARCHAR(255),
  hhid_142 VARCHAR(255),
  crop_fields_total_collected VARCHAR(255),
  crop_fields_total_units VARCHAR(255),
  crop_fields_firedwood VARCHAR(255),
  crop_fields_fertilizer VARCHAR(255),
  crop_fields_constrction VARCHAR(255),
  crop_fields_biogas VARCHAR(255),
  crop_fields_sold VARCHAR(255),
  crop_fields_revenues VARCHAR(255),
  crop_fields_wasted VARCHAR(255),
  crop_fields_notes VARCHAR(255),
  on_farm_total_collected VARCHAR(255),
  on_farm_total_units VARCHAR(255),
  on_farm_firedwood VARCHAR(255),
  on_farm_fertilizer VARCHAR(255),
  on_farm_constrction VARCHAR(255),
  on_farm_biogas VARCHAR(255),
  on_farm_sold VARCHAR(255),
  on_farm_revenues VARCHAR(255),
  on_farm_wasted VARCHAR(255),
  on_farm_notes VARCHAR(255),
  off_farm_total_collected VARCHAR(255),
  off_farm_total_units VARCHAR(255),
  off_farm_firedwood VARCHAR(255),
  off_farm_fertilizer VARCHAR(255),
  off_farm_constrction VARCHAR(255),
  off_farm_biogas VARCHAR(255),
  off_farm_sold VARCHAR(255),
  off_farm_revenues VARCHAR(255),
  off_farm_wasted VARCHAR(255),
  off_farm_notes VARCHAR(255)
);