CREATE TABLE non_ruminants (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  non_ruminant_no INT,
  district_81 VARCHAR(255),
  ward_81 VARCHAR(255),
  village_81 VARCHAR(255),
  hhid_81 VARCHAR(255),
  non_ruminant_type VARCHAR(255),
  gender_ownership VARCHAR(255),
  Total_kept VARCHAR(255),
  Adult_females VARCHAR(255),
  Adult_males VARCHAR(255),
  Young VARCHAR(255),
  newly_acquired VARCHAR(255),
  no_added VARCHAR(255),
  way_acquired VARCHAR(255),
  other_way_acquired VARCHAR(255),
  if_purchased VARCHAR(255),
  notes_non_ruminant_livestock VARCHAR(255)
);