CREATE TABLE short_rains_crops_products (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  district_281 VARCHAR(255),
  ward_281 VARCHAR(255),
  village_281 VARCHAR(255),
  hhid_281 VARCHAR(255),
  short_rains_crops_products VARCHAR(255),
  short_rains_production_Quantity VARCHAR(255),
  short_rains_production_Quantity_units VARCHAR(255),
  short_rains_Hhfood_consumption_Qty VARCHAR(255),
  short_rains_Hhfood_consumption_Qty_units VARCHAR(255),
  short_rains_Payment_in_kind_quantity VARCHAR(255),
  short_rains_Payment_in_kind_quantity_units VARCHAR(255),
  short_rains_other_Qty VARCHAR(255),
  short_rains_other_Qty_units VARCHAR(255),
  short_rains_Livestock_feeding_Qty VARCHAR(255),
  short_rains_Livestock_feeding_Qty_units VARCHAR(255),
  short_rains_kept_as_seed_Qty VARCHAR(255),
  short_rains_kept_as_seed_Qty_units VARCHAR(255),
  short_rains_sales_Qnty VARCHAR(255),
  short_rains_Sales_quantity VARCHAR(255),
  short_rains_Sales_units VARCHAR(255),
  short_rains_Sales_total_value VARCHAR(255),
  short_rains_Sales_income_control VARCHAR(255),
  short_rains_main_buyer VARCHAR(255),
  short_rains_stored_for_Dry_Season VARCHAR(255)
);